#!/bin/bash
#
# ip jargi avuti kontrollimine
#for((nr=1; nr=10; nr++))
for ip in 172.23.13.{20..50}
do
  #ip=172.23.13.$nr
ping -c 1 $ip > /dev/null #valjund kustutatud
# ctrl
if [ $? -eq 0 ]; then
	# kui $? on 0 - korras
	echo "$ip - online"
else
   echo "$ip - offline"
fi
done
