#!/bin/bash
#
# keskkonna ja oma muutujate kasutamine
#
# kasutame keskkonna muutuja nimega $USER
# tervitame kasutaja
echo "Tere, $USER!"
# kuupäeva väärtuse loomine
# defineermine vastava väärtusega muutuja
kuupaev=`date +'%d. %B'`
# väljastamine kuupäev koos seletusega
echo "Täna on $kuupaev"
