#!/bin/bash
#
# keskkonna ja oma muutujate kasutamine
#
# kasutame keskkonna muutuja nimega $USER
# tervitame kasutaja
echo "Tere, $USER!"
# kuupäeva väärtuse loomine
# defineermine vastava väärtusega muutuja
kuupaev=`date +'%d. %B'`
# väljastamine kuupäev koos seletusega
echo "Täna on $kuupaev"
# kella väärtuse loomine
# defineerime vastava väärtusega muutuja
kell=`date +'%H:%M'`
# väljastamine kell koos seletusega
echo "Kell on $kell"
# väljastame kalendrit
kalender=`cal`
# väljastame sõnumit
echo "Antud kuu kalender:"
echo "-------------------"
echo "$kalender"
echo "-------------------"
